### ISSUE TITLE
speech button broken

### ISSUE THREAD

**Issue by nmohamed** [greneroom/Hi-Reddit#18]
stuff broke after david's pull request to speech button debug. there is an infinite error loop.

**Comment by davidabrahams** [comment]
Oh oops did I screw something up? What was the infinite loop error?

**Comment by nmohamed** [comment]
the
[dontListen() also calls sr.stopListening() which causes an error (since it wasn't listening at that point) which calls dontListen() which also calls sr.stopListening() which causes an error...](https://github.com/greneroom/Hi-Reddit/pull/19)
