### ISSUE TITLE
Asks to download mp3 after reading response

### ISSUE THREAD

**Issue by nmohamed** [greneroom/Hi-Reddit#24]
Did this on Nora's phone. We asked the same question and same result again, and didn't get asked to download it.

**Comment by YuzhongHuang** [comment]
http://androidforums.com/threads/download-high-quality-voice-file.789236/

**Comment by LucyWilcox** [comment]
I never get this on either of my phones... @nmohamed is this still happening to you?

**Comment by YuzhongHuang** [comment]
Yes, the link I posted above is a discussion of that problem. It seems that on some old version phones, any app that uses sound has the same problem. So I think it is a phone thing instead of our app's issue
