### ISSUE TITLE
Dead word: "Google internship"

### ISSUE THREAD

**Issue by YuzhongHuang** [greneroom/Hi-Reddit#41]
Throws Null pointer exception. Kills the app every time I said it.

**Comment by YuzhongHuang** [comment]
Another dead sentence: help me find my way back to the dining hall

**Comment by YuzhongHuang** [comment]
Another: I knew you were trouble

**Comment by YuzhongHuang** [comment]
Yet another: you're going to crach, right?

"you stupid app" works too

**Comment by nmohamed** [comment]
i tried some of these and just get the toast with "no comment available"
I think it might be a problem with your branch.

**Comment by YuzhongHuang** [comment]
Yes, sorry for that guys

**Comment by YuzhongHuang** [comment]
@nmohamed Did you test the most up-to-date master, since I test the master again, and it crashes.

**Comment by YuzhongHuang** [comment]
I use the debug mode, it seems to have problem in the function pickComment() in reddit searcher

**Comment by nmohamed** [comment]
hmm... i thought i was since it tells me i'm up too date with master but clearly i'm not now that i've checked. this means something went wrong with whatever we've merged since after tuesday afternoon

**Comment by LucyWilcox** [comment]
Also I was thinking if it can't get something from the user input it could just use one of the random words from the shake method.
