### ISSUE TITLE
speech doesn't work

### ISSUE THREAD

**Issue by YuzhongHuang** [greneroom/Hi-Reddit#57]
have some bug in lovely-UI with the speaker

**Comment by YuzhongHuang** [comment]
Done

**Comment by nmohamed** [comment]
the bug is: app won't speak unless you go into info fragment, which turns speech on, and then go back, which turns speech off.
where it's an issue: lovely-ui

**Comment by YuzhongHuang** [comment]
yes, I fix this bug

**Comment by LucyWilcox** [comment]
Did you make  pull request anywhere?

**Comment by YuzhongHuang** [comment]
No, but I commited to adding-string branch. I think we will review the adding-string pull request later so it will probably be fine?

**Comment by LucyWilcox** [comment]
Okay!
