### ISSUE TITLE
network problem

### ISSUE THREAD

**Issue by YuzhongHuang** [greneroom/Hi-Reddit#58]
error was caught before the network issue is addressed in lovely-ui

**Comment by nmohamed** [comment]
? is this that we fixed a problem or that there is a probleM?

**Comment by LucyWilcox** [comment]
It's still an issue.

**Comment by YuzhongHuang** [comment]
There is no network issue when I was testing branch adding-strings

**Comment by YuzhongHuang** [comment]
It's working alright..

**Comment by LucyWilcox** [comment]
On my branch it's still giving me the standard errors not the no wifi errors when I disable wifi and data. And adding-strings is my branch so...

What do you mean by it's working?

**Comment by YuzhongHuang** [comment]
In my phone, it just read out our strings when there is no wifi like "life without wifi is hard" or so.

**Comment by YuzhongHuang** [comment]
I also tested on branch lovely-ui, and it works too.

**Comment by LucyWilcox** [comment]
Weird... well okay I guess. Maybe we can look more at it today. But for now I guess it's just the other bug.

**Comment by nmohamed** [comment]
I'm on lovely-ui and it doesn't work. It just gives me the errorCallback error messages
